import os

PRIMARY_REDIS_DATASOURCE_URL = os.environ.get("PRIMARY_REDIS_DATASOURCE_HOST", "localhost")
PRIMARY_REDIS_DATASOURCE_PORT = os.environ.get("PRIMARY_REDIS_DATASOURCE_PORT", 6379)
PRIMARY_REDIS_DATASOURCE_PASSWORD = os.environ.get("PRIMARY_REDIS_DATASOURCE_PASSWORD", None)
REDIS_CONFIGURATION_POOL_CONFIG_MAX_ACTIVE = os.environ.get("REDIS_CONFIGURATION_POOL-CONFIG_MAX-ACTIVE", 5)
REDIS_CONFIGURATION_POOL_CONFIG_TIMEOUT = os.environ.get("REDIS_CONFIGURATION_POOL-CONFIG_TIMEOUT", 30)